cvmfsConfig:
  default.local:
    data:
      default.local: |
        CVMFS_USE_GEOAPI=yes
        CVMFS_HTTP_PROXY=DIRECT
  config.d:
    data:
      unpacked.cern.ch.conf: |
        CVMFS_QUOTA_LIMIT=4000
      sft.cern.ch.conf: |
        CVMFS_QUOTA_LIMIT=4000
      unpacked.infn.it.conf: |
        CVMFS_QUOTA_LIMIT=4000
        CVMFS_SERVER_URL="http://cvmfs-stratum1-cnaf.cloud.infn.it:8000/cvmfs/@fqrn@;http://cvmfs-stratum1-bari.cloud.infn.it:8000/cvmfs/@fqrn@"
        CVMFS_KEYS_DIR="/etc/cvmfs/config.d"
        CVMFS_DEFAULT_DOMAIN="infn.it"
        X509_CERT_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
      common.infn.it.pub: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn7MHm+TkYjyLmuQKOL2x
        IU/DPHiRusqzVjvnILGaDfX2J9/DNwyJ8G3JNhP9Ivm5XuoNm+rgGxweHvMTC1/7
        S9I2d5Ur4AyGDoXXmFj+nmd8yi+cU+n2AFaF9BAtr8pJZSVDISsNsa7MXqwc4AHi
        E3lc2xxDH9uH2t6dOaNvAEB9T/LhqYJg7UlSJaXm4kKT0ys/C6EL5KlpQPkHKYGO
        +ucZpilj/v9cuTu7N2GPLXHtU8m02CfY6N4BC1PoEdhZ6ZirAcTDJU6hENnzL+2h
        K4p5DRuZxuROjYozkhLp6N1zm1ih+lRUnsU2zXyOpTFOEP2kZzS++yKi+l/jd3+b
        fwIDAQAB
        -----END PUBLIC KEY-----
